#!/bin/bash
echo "Enter salary"
read sal
if [ "$sal" -lt 10000 ]; then
	echo no tax
elif [ "$sal" -gt 10000 ] $$ [ "$sal" -lt 25000 ]; then
	echo 5% tax
elif [ "$sal" -gt 25000 ]; then
        echo 10% tax
else;
	echo none
fi	
