#!/bin/bash
echo "Enter salary"
read sal
if [ "$sal" == 10000 ]; then
	echo 2%tax
elif [ "$sal" -lt 10000 ]; then
	echo notax
elif [ "$sal" -gt 10000 ] && [ "$sal" -le 25000 ]; then
	echo 5% tax
elif [ "$sal" -gt 25000 ]; then
        echo 10% tax
fi	
